import Testing
import SwiftUI
@testable import KippuLog

/// End-to-end: render a ticket to an image, then run it back through the
/// *real* Vision OCR + RouteDetector + gazetteer. The rendered plate draws
/// its route arrow as a vector shape (no arrow glyph for OCR to find), so
/// this genuinely exercises the geometry/whitespace station-pairing path.
@MainActor
struct RecognitionIntegrationTests {
    @Test func readsRenderedShinkansenPlate() async throws {
        let ticket = Ticket.samples[1] // 東京 → 京都, のぞみ
        let image = try render(ticket)

        let lines = (try? await TicketRecognizer.recognizeLines(in: image)) ?? []
        #expect(!lines.isEmpty)

        let parsed = TicketTextParser.parse(ocrLines: lines)
        #expect(parsed.fromStation == "東京")
        #expect(parsed.toStation == "京都")
    }

    @Test func readsRenderedEntrancePlate() async throws {
        let ticket = Ticket.samples[5] // 尾道 入場券
        let image = try render(ticket)

        let lines = (try? await TicketRecognizer.recognizeLines(in: image)) ?? []
        let parsed = TicketTextParser.parse(ocrLines: lines)
        #expect(parsed.fromStation == "尾道")
    }

    /// Hard-mode fixture: small, rotated, soft-focused green stock with
    /// fare-zone endpoints, photographed on a dim desk. The whole pipeline —
    /// flatten → OCR → route — must still land. (Generated by
    /// `swift scripts/gen_test_photos.swift`; skipped when absent.)
    @Test func readsHardModePhotoEndToEnd() async throws {
        let path = "/tmp/kippu_test_hard.png"
        guard let photo = UIImage(contentsOfFile: path) else {
            Issue.record("fixture missing — run scripts/gen_test_photos.swift")
            return
        }
        let result = await TicketRecognizer.flatten(photo)
        let lines = (try? await TicketRecognizer.recognizeLines(in: result.image)) ?? []
        #expect(!lines.isEmpty)

        let parsed = TicketTextParser.parse(ocrLines: lines)
        #expect(parsed.fromStation == "東京都区内")
        #expect(parsed.toStation == "京都市内")
        #expect(parsed.price == 8910)
        #expect(parsed.kind == .joshaken)
    }

    /// Mercari-style set photo: several tickets in frame. The crop must
    /// land on the dominant centred ticket — verified by the scan aspect
    /// (a clean MARS cut ≈ 1.49) and by its stations parsing through.
    @Test func picksDominantTicketAmongMany() async throws {
        guard let photo = UIImage(contentsOfFile: "/tmp/kippu_test_pair.png") else {
            Issue.record("fixture missing — run scripts/gen_test_photos.swift")
            return
        }
        let result = await TicketRecognizer.flatten(photo)
        #expect(result.tight)
        let aspect = result.image.size.width / max(result.image.size.height, 1)
        #expect(aspect > 1.32 && aspect < 1.65)

        let lines = (try? await TicketRecognizer.recognizeLines(in: result.image)) ?? []
        let parsed = TicketTextParser.parse(ocrLines: lines)
        #expect(parsed.fromStation == "東京")
        #expect(parsed.toStation == "新大阪")
    }

    /// One-sided hard shadow: the halo inflates the first quad on a single
    /// edge; the second pass must shave it. Verified by the scan aspect.
    @Test func shavesOffsetShadowResidue() async throws {
        guard let photo = UIImage(contentsOfFile: "/tmp/kippu_test_shadow.png") else {
            Issue.record("fixture missing — run scripts/gen_test_photos.swift")
            return
        }
        let result = await TicketRecognizer.flatten(photo)
        #expect(result.tight)
        let aspect = result.image.size.width / max(result.image.size.height, 1)
        #expect(aspect > 1.32 && aspect < 1.65)
    }

    // MARK: helpers

    private func render(_ ticket: Ticket) throws -> UIImage {
        let aspect = TicketArtView.aspect(for: ticket.kind)
        let width: CGFloat = 760
        let renderer = ImageRenderer(
            content: TicketArtView(ticket: ticket)
                .frame(width: width, height: width / aspect)
        )
        renderer.scale = 2
        guard let image = renderer.uiImage else {
            throw CocoaError(.fileWriteUnknown)
        }
        return image
    }
}
